### ISSUE TITLE
HLT name mismatch

### ISSUE THREAD

**Issue by jhgoh** [cms-kr/TZWi#64]
Some failures during ntupling.

```
Traceback (most recent call last):
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/bin/slc6_amd64_gcc700/nano_postproc.py", line 51, in <module>
    p.run()
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 131, in run
    (nall, npass, timeLoop) = eventLoop(self.modules, inFile, outFile, inTree, outTree)
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/python/PhysicsTools/NanoAODTools/postprocessing/framework/eventloop.py", line 48, in eventLoop
    m.beginFile(inputFile, outputFile, inputTree, wrappedOutputTree)
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/python/TZWi/TopAnalysis/postprocessing/CombineHLT.py", line 62, in beginFile
    self.initReaders(inputTree)
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/python/TZWi/TopAnalysis/postprocessing/CombineHLT.py", line 69, in initReaders
    setattr(self, "b_"+name, tree.valueReader(name))
  File "/cms/ldap_home/jhgoh/work/CMS/NanoAOD/CMSSW_10_2_11/python/PhysicsTools/NanoAODTools/postprocessing/framework/treeReaderArrayTools.py", line 38, in getValueReader
    if not tree.GetBranch(branchName): raise RuntimeError, "Can't find branch '%s'" % branchName
RuntimeError: Can't find branch 'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL'
```

**Comment by jhgoh** [comment]
files with problem: 
```
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/00ECD77A-DD01-9F4D-91C9-7FD872324C92.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/03ADC41C-9ECC-9844-9048-A0F311ABE6FF.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/09137909-A881-D443-9C6A-F6DF5018AB55.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/0D66B81D-46E6-E44F-B7D1-8DCF8FDF3490.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/20E23E5B-AA9F-B847-B2EF-E0D66D6E2438.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/28580FFC-D1E3-D44F-ACB4-88D93C1302AD.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/302630C7-D5B7-1D4A-9525-9936469659A7.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/47489D75-9B48-FD4B-93F9-AB7169CFBED0.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/4EB174EC-E6E8-A746-A863-4CAD83FC36DB.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/5D5D9487-2DDA-1144-B106-4F3D1457FE1F.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/63F64E53-D8C0-F242-98A6-7DDA2EF25586.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/69BD5558-9E0E-914B-90B0-5F60D3832247.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/69D09690-949C-1244-BD49-769D4F5C35E2.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/776B87E1-C260-0248-8C70-21B09167D563.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/8670D43A-D492-A24A-8354-C14BF9B47F7C.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/8AC92876-C127-0E4A-924D-FEBB3A7CEF97.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/AB1B8605-166C-6246-AD52-BF69FD0BD27D.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/BA2314B3-830D-B04C-8D8B-E4020FB70BE1.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/CBBCC87C-2DC2-E142-9720-7FA864BE0DBD.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/FAE75F95-3C85-334A-939B-53495B8DB326.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/10000/FC378606-F97D-5749-BB3E-A18B24B7AC57.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/04D49D0F-55FD-234F-8555-7FEBA9D489FD.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/068047BD-5595-954E-BB8F-D33D811B4852.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/1045EDCA-907C-8F4D-8537-13D439929FF0.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/15637DFD-F3FC-094E-A8BF-07986D627241.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/1C9B7A9F-8CCF-9142-B23F-13BED2445BF6.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/24C0AFBC-4CC2-AA4C-BF33-92C0415B40FC.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/294BBEC3-2017-9A4E-9AD8-1A4E54E75438.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/3940C521-CBDE-414C-BE90-E7F51085ACB8.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/3C6FE883-552A-E64E-B72D-B57E987FDE6A.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/3DE4E39B-ACE0-7A4C-ADCE-A359F9BCDC1C.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/3F104328-6976-C047-AFC1-2FAB2A720DB9.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/3FDC8B22-303B-1942-BEEF-347CBA07CA80.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/42A2BD8D-BAFB-0745-9893-5B134EBDA0A8.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/46F89E46-758F-4F47-8827-8D55F40D9BDB.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/50E77458-D816-8F4B-8912-D07E94B9F1A3.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/53FA8545-AA50-104D-89D1-E57FFE2B748D.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/5618F12F-4507-594C-A6A9-7E66CEB84D05.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/60BAC94B-66C1-7040-8B64-0CDFFA835CFB.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/6361A123-25D6-B94A-A723-D19830052D15.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/642A9C06-C98B-0144-B419-083CDC9EC86A.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/6587A848-318F-A14E-8E32-D99B40DE55AE.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/65EB512D-EF28-5246-8DBC-259C2A054820.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/7066BE1B-7FB4-7B4F-A2A4-AAAEC82B8AC9.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/779A2E92-3359-3240-92B8-9F689C19F8EA.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/7BABABA9-D81F-F246-83A5-E76B3A8CCB0F.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/7C47B4CC-1B51-4C41-A03C-C4FFE8A04570.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/828371A4-47FE-A34A-971C-2070640D6609.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/83A01FAD-B775-B843-AF1B-57D59E98A59F.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/86CEEDB8-703B-5F4C-A073-623C0FE2416D.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/8713F95E-BDCE-AD47-8081-0F551D1528D2.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/8857D38C-3312-EA4F-B3F4-83C892A89FC3.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/8EEA4186-7AA7-9047-AEA0-455E187467CE.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/96043043-AEF8-A842-B350-8E16FC69350B.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/9628D339-A9CB-9F43-9013-42CFDA9A803B.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/9E701BDB-544C-B64A-A750-3C9833BB4F59.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/9EE969CD-FFE0-CD4A-8BD3-497968025BDA.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/9F6546B5-F9B3-554D-9EF3-332D5CBE1AB3.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/A8C5E011-D6A7-7943-B32F-684C08914D1A.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/AAA84334-5597-1541-8DCB-342E9A01529B.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/AB1EE588-8C24-DD4F-8A9B-430AB3225A85.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/B9C74E41-FF97-E342-8F8C-5DA15D10F50D.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/BBEE6082-293D-664D-B59E-FA55BD4C2C6A.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/D1C79688-11A1-3344-9F24-2A7E16F9A4CE.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/D44C2C12-24AF-EB48-80BE-2CD540F54105.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/E178B047-F0D0-FD41-BAF5-0A54D62F83A2.root
root://cms-xrdr.sdfarm.kr//xrd/store/data/Run2017B/SingleMuon/NANOAOD/Nano14Dec2018-v1/90000/E314FF75-8F19-584B-816D-21CE9919404D.root
```
